### ISSUE TITLE
How to implement a common selection query

### ISSUE THREAD

**Issue by lym121** [uber/aresdb#106]
In the 'Ares Query Language' document, the last example describes that "While AQL is designed primarily for time series aggregates, it is also possible to express non-aggregate queries, such as selection queries." but when i Use 1 or any constant as the measure expression, it can not run. I want to know how to implement a common selection query.can you give me a example or a detailed document about the Ares Query Language.

**Comment by shz117** [comment]
we are actively working on it. hang on tight!

**Comment by shz117** [comment]
this is done as documented (use 1 as measure).
we also added sql support so user won't need to write this hacky query.
