### ISSUE TITLE
replace rdkafka with sarama to mitigate compiling issue

### ISSUE THREAD

**Issue by voyager-dw** [uber/aresdb#303]
**Is your feature request related to a problem? Please describe.**
The compiler spent a lot of time on the compilation of rdkafka and sometimes stuck

**Describe the solution you'd like**
Replace rdkafka with simpler kafka consumer like Sarama

**Comment by hasitpbhatt** [comment]
This was resolved in a3c4960069720ccda79f02582e8f5da3a70d520b.

**Comment by hasitpbhatt** [comment]
Duplicate of #306
