### ISSUE TITLE
Failed to use swagger in docker

### ISSUE THREAD

**Issue by zingdle** [uber/aresdb#320]
**Describe the bug**
Failed to use swagger in docker

**To Reproduce**
- Follow: https://github.com/uber/aresdb/blob/master/docker/README.md
- Visit http://my-ip:9374/swagger/ (`my-ip` is the docker host's ip)

Chrome console output:

```
Refused to apply style from 'http://my-ip:9374/node_modules/swagger-ui-dist/swagger-ui.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
(index):14 GET http://my-ip:9374/node_modules/swagger-ui-dist/swagger-ui-bundle.js net::ERR_ABORTED 404 (Not Found)
(index):15 GET http://my-ip:9374/node_modules/swagger-ui-dist/swagger-ui-standalone-preset.js net::ERR_ABORTED 404 (Not Found)
```

**Comment by ceciliacsilva** [comment]
I was having the same problem, I fixed installing the necessary js packages.

```bash
# cd api/ui
# npm install
```

**Comment by zingdle** [comment]
Thanks @ceciliacsilva ! It works like a charm.

In Dockerfile [L34](https://github.com/uber/aresdb/blob/8eb4d292db94aa4ef9651b1f4ab720c8621048d0/docker/Dockerfile#L34) it has done a [npm-install](https://github.com/uber/aresdb/blob/8eb4d292db94aa4ef9651b1f4ab720c8621048d0/CMakeLists.txt#L310). Don't know why we have to do it manually.
