### ISSUE TITLE
CUDA 9.2?

### ISSUE THREAD

**Issue by kabrin** [uber/aresdb#345]
I know the documentation states CUDA 9.1 is required, but has there been any testing done with CUDA 9.2? Does that work with any version of Aresdb?

**Comment by shz117** [comment]
CUDA 9.2 should be compatible with code written for earlier versions.
with CUDA 9.2 you want to make sure your driver version is greater than 396.26 though.
reference: https://docs.nvidia.com/deploy/cuda-compatibility/index.html
