### ISSUE TITLE
Provide sample dataset and queries

### ISSUE THREAD

**Issue by jshencode** [uber/aresdb#60]
**Is your feature request related to a problem? Please describe.**
Provide sample dataset and queries

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shz117** [comment]
how about generating data on the fly?
something like `aresdb datagen --size=large -o ./dataset`
it would bel light weight and useful to use with benchmarks (e.g. with different GPUs)

**Comment by jshencode** [comment]
resolved by #92
