### ISSUE TITLE
Add documentation, usage examples, and client/drivers

### ISSUE THREAD

**Issue by impredicative** [uber/aresdb#67]
Do you intend to provide documentation, usage examples, and clients/drivers for various programming/REST/GraphQL languages, etc.? At this time the project looks to be more hype than anything else, just like a lot of other such projects by Uber. I don't follow why it was released publically without these basics.

**Comment by shz117** [comment]
You can find documentations in README and link to eng blog with detailed design from there. There are also docs in Wiki.

We do have plans to add query client #55  and example code and data set #60 .
