### ISSUE TITLE
schema creation with default values and validation of configs

### ISSUE THREAD

**Issue by jshencode** [uber/aresdb#90]
**Describe the bug**
currently, user create schema through api and did not fill in table configs will produce invalid table schema and cause server panic once trying to ingest data until server restart

**To Reproduce**
1. create table through api without table config
2. ingest data
3. restart server

**Expected behavior**
panic at step 2
return normal at step 3

**Comment by shz117** [comment]
as discussed offline, it's likely caused by default config merged on read path instead of write path.
proposed fix:
 1. fill defaults on write path, and persist on disk
 2. optionally add validation rules against invalid table config
